### ISSUE TITLE
UI: 화면 구성 변경

### ISSUE THREAD

**Issue by marmot8080** [marmot8080/Soom-Charm#13]
개인적으로 지금의 화면 구성이 조금 복잡할 수도 있다고 생각되는데 지금보다 화면 구조의 복잡성을 줄일 수 있을 것 같다고 생각합니다.
우선 제 구상은 bottomNavigationBar를 이용해서 3가지 이동으로 설정하고 그 3가지를 gps, home, my profile로 하는 것입니다.
세부적인 구상은 이렇습니다.

1. setting page와 기록 확인 페이지를 my profile 페이지로 통합
--> my profile 페이지에서 두 개의 페이지로 갈 수 있도록 해도 되고, 기존의 setting 페이지를 my profile 페이지로 사용하고 기록 확인 페이지 이동을 추가하는 방법도 가능
2. 기존 네비게이션 바의 기록 확인 페이지로의 이동 대신 gps tracker 기능으로의 이동으로 대체
3. 화면 상단의 하트 옆 +를 누를 시 상점 페이지로 이동
4. home 버튼을 통해 game stage 페이지로 이동

상점의 경우 하트 구매 외의 다른 사용처가 없으니 상단 +버튼으로도 충분히 대체 가능할 것이라고 생각했습니다.
아니면 저는 네비게이션 바의 이동을 3가지로 생각하고 구상한 것이지만 다른 중요한 기능들이 가려진다고 생각되시면 아예 5가지 정도로 설정해서 더 많은 이동을 나열하는 방법도 있을 것 같습니다.

+이렇게 될 경우 기존 main page 파일을 기준으로 통합하도록 수정하게 될 것 같습니다.

### 구조
mainPage (bottomNavigationBar)
　│
　├─ GPS_tracker_screen(gps)
　├─ game_stage_screen(home)
　└─ my_profile_screen(my profile)
　　　　　│
　　　　　├─ settingPage
　　　　　└─ 기록 확인 페이지
　　　　　└─ + 랭킹 페이지도 가능

**Comment by Hyunjiiing** [comment]
바텀바에서 상점 아이콘 대신에 + 아이콘으로 상점 페이지를 가도록 하는 것은 엄청 좋은 아이디어 같습니다.
또 gps, home, my profile을 하단바에 위치시키는 것도 동의하는 바입니다.
하지만 설정 페이지와 기록 확인 페이지를 my profile 페이지로 합칠 경우 메인 기능 중 일부라고 생각했던 기록 확인 페이지가 덜 중요한 설정 페이지와 동등한 중요도를 가지는 것처럼 보이게 될까 우려되는거 같습니다. 따라서 settings, gps, home, chart 4개로 하단바를 구성하는것은 어떨까요?

**Comment by marmot8080** [comment]
그럼 my profile에서 기본 사용자 정보 + 누적 기록 그래프를 확인 가능하도록 하고 추가적으로 설정 페이지로 이동 가능하게 하거나 상단에 하트 옆 등에 설정 아이콘을 배치하는 건 어떨까요?

**Comment by Hyunjiiing** [comment]
오 좋습니다! 다른 의견 없으면 바텀바는 gps, home, my profile로 통일하고 my profile에 차트를 넣고 설정은 또 그 안에서 들어갈 수 있도록 합시다.

**Comment by marmot8080** [comment]
넵 그러면 main_screen 파일은 테스트 용으로 남겨두고 mainPage 화면을 기준으로 구성해보겠습니다.

**Comment by marmot8080** [comment]
추가적으로 파일명 형식도 통일하려고 하는데 main_page 이런 식으로 할까요? 아니면 mainPage 이런 식으로 할까요?

**Comment by Hyunjiiing** [comment]
어떤 방식으로 통일해도 괜찮을거 같긴한데 저는 mainPage 이게 더 좋은거 같습니다.
근데 저거로 하려면 앞 글자도 대문자로 해야할 거 같아요 자꾸 gpt에 넣으면 MainPage로 수정되어 나와서 번거롭더라구요

**Comment by snsthqhr** [comment]
확인했습니다! 제가 이해한게 맞다면 마이페이지에 사용자 정보 + 변화량 페이지가 들어가게 되는게 맞나요?

**Comment by marmot8080** [comment]
네 사용자 기본정보 + 변화량 + setting 페이지 이동 이렇게 3가지를 포함하는 것으로 생각하고 있습니다.
