### ISSUE TITLE
이 이미지 파일 asset/image 폴더에 올려주실 수 있나요?

### ISSUE THREAD

**Issue by snsthqhr** [marmot8080/Soom-Charm#19]
![image](https://github.com/user-attachments/assets/3f61c872-3ba2-4104-b3c8-9fa7477ea300)
![image](https://github.com/user-attachments/assets/20d77cbe-31e8-4b18-b9a2-f862b10803b0)
프로필 이미지랑, 상점 이미지, 설정 이미지, 그래프 이미지 부탁드려요!

**Comment by Hyunjiiing** [comment]
![shop](https://github.com/user-attachments/assets/4f55656e-689e-44ac-a47e-7e033732c68b)
![chart](https://github.com/user-attachments/assets/b7abb9a5-b746-4ff5-b0b1-814b6bf8f568)
![user](https://github.com/user-attachments/assets/cbed4b84-8303-44cb-b72c-4fccbd28fab0)
![settings](https://github.com/user-attachments/assets/2f11485c-4424-494b-a467-e250505eefe0)

**Comment by Hyunjiiing** [comment]
화질 떨어질거 같아서 톡으로도 보내드릴게요!
