### ISSUE TITLE
project management: GPS 사용 관련

### ISSUE THREAD

**Issue by marmot8080** [marmot8080/Soom-Charm#5]
### GPS 사용여부
GPS의 경우 건물 내부나 터널 안에 있을 경우나, 전파를 막는 구조물이 존재할 경우 제대로 작동하지 않을 수 있다고 합니다.
하지만 외부에서 걷는 경우를 상정했을 때, 일반적으로는 큰 문제가 없다고 생각됩니다.
그에 반해 만보기를 사용하게 되면 직접 걷지 않더라도 만보기 횟수를 올릴 수 있어 GPS를 활용하는 방법이 더 좋다고 생각되어 우선 GPS를 활용하는 방향으로 진행해보려고 합니다.

### 백그라운드 실행
조사해봤을 때, GPS의 경우 휴대폰의 자원을 많이 요구하는 것으로 확인되어 백그라운드에서의 상시 실행에는 어려움이 있을 것 같습니다.

**Comment by Hyunjiiing** [comment]
그런 의미에서 GPS를 활용하고자 하는 것이라면 좋다고 생각합니다.
그렇다면 스테이지 잠금 해제 요소가 걸음 수가 아니라 특정 장소나 건물까지 가는 것이 되는 것인가요?

**Comment by marmot8080** [comment]
기능을 구현해봤는데 단위시간마다 하기보다는 거리마다 총 거리를 업데이트하는 방식이 더 나아보여서 우선 10미터마다 업데이트 되도록 구현하였습니다.
gps의 정확도 이슈로 몇 미터 정도의 오차가 있을 수 있다고 하여 우선 10미터마다로 설정하였습니다만, 테스트 해보시고 오차가 크다고 느끼신다면 단위거리를 더 늘리도록 하겠습니다.
